// Custom signup/potluck types.
// These are NOT auto-generated by `supabase gen types` and must be maintained manually.
// They correspond to views and RPC return types that the CLI does not emit typed interfaces for.

export type SignupFormType = 'event' | 'general' | 'potluck';
export type SignupFieldType = 'text' | 'email' | 'phone' | 'boolean' | 'select' | 'textarea' | 'date' | 'number';
export type SignupStatus = 'confirmed' | 'waitlisted' | 'cancelled';

export interface SignupForm {
  id: string;
  form_type: SignupFormType;
  event_id: string | null;
  title: string;
  description: string | null;
  is_active: boolean;
  max_signups: number | null;
  deadline: string | null;
  allow_guest_signup: boolean;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface SignupFormField {
  id: string;
  form_id: string;
  field_key: string;
  field_label: string;
  field_type: SignupFieldType;
  is_required: boolean;
  is_standard: boolean;
  options: string[] | null;
  placeholder: string | null;
  sort_order: number;
}

export interface SignupResponse {
  id: string;
  form_id: string;
  person_id: string | null;
  submitted_by: string | null;
  respondent_name: string;
  respondent_email: string | null;
  respondent_phone: string | null;
  status: SignupStatus;
  created_at: string;
  updated_at: string;
}

export interface SignupResponseValue {
  id: string;
  response_id: string;
  field_id: string;
  value: string | null;
}

export interface SignupFormSummary {
  form_id: string;
  form_title: string;
  form_description: string | null;
  form_type: SignupFormType;
  event_id: string;
  event_title: string;
  event_start: string;
  event_end: string;
  event_location: string | null;
  max_signups: number | null;
  deadline: string | null;
  confirmed_count: number;
  is_active: boolean;
  total_items: number | null;
  fully_claimed_items: number | null;
  total_claims: number | null;
}

export interface SignupItemGroup {
  id: string;
  form_id: string;
  title: string;
  sort_order: number;
}

export interface SignupItem {
  id: string;
  group_id: string;
  form_id: string;
  name: string;
  description: string | null;
  quantity_needed: number;
  sort_order: number;
}

export interface SignupItemClaim {
  id: string;
  item_id: string;
  form_id: string;
  person_id: string | null;
  claimed_by: string;
  claimant_name: string;
  note: string | null;
  created_at: string;
}

export interface PotluckFormDetailRow {
  item_id: string;
  form_id: string;
  item_name: string;
  item_description: string | null;
  quantity_needed: number;
  item_sort: number;
  group_id: string;
  group_title: string;
  group_sort: number;
  event_id: string;
  form_title: string;
  is_active: boolean;
  deadline: string | null;
  claim_count: number;
  claims: {
    claim_id: string;
    person_id: string | null;
    claimant_name: string;
    claimed_by: string;
    note: string | null;
    created_at: string;
  }[] | null;
}

export interface MySignupForm {
  form_id: string;
  form_title: string;
  form_description: string | null;
  form_type: SignupFormType;
  event_id: string;
  event_title: string;
  event_start: string;
  event_end: string;
  event_location: string | null;
  max_signups: number | null;
  deadline: string | null;
  confirmed_count: number;
  my_signup_status: 'confirmed' | 'waitlisted' | null;
  total_items: number | null;
  fully_claimed_items: number | null;
  total_claims: number | null;
  my_claimed_items: string[] | null;
}

export interface SignupResponseDetail {
  id: string;
  form_id: string;
  person_id: string | null;
  submitted_by: string | null;
  respondent_name: string;
  respondent_email: string | null;
  respondent_phone: string | null;
  status: SignupStatus;
  created_at: string;
  updated_at: string;
  custom_fields: Record<string, string> | null;
  person_photo_url: string | null;
  submitter_name: string | null;
}
