import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },
  scrollView: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 },
  loadingText: { fontSize: 15, color: '#6B7280' },
  headerCard: { alignItems: 'center', paddingVertical: 24, paddingHorizontal: 20, gap: 6 },
  pageTitle: { fontSize: 22, fontWeight: '700' as const, color: '#1F2937', marginTop: 8 },
  pageSubtitle: { fontSize: 14, color: '#6B7280' },
  card: { backgroundColor: '#FFFFFF', marginHorizontal: 16, marginBottom: 12, borderRadius: 14, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 6, elevation: 1 },
  churchInfoRow: { marginBottom: 14, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  churchInfoName: { fontSize: 16, fontWeight: '700' as const, color: '#1F2937', marginBottom: 4 },
  churchInfoDetail: { fontSize: 13, color: '#6B7280', marginBottom: 2 },
  churchInfoHint: { fontSize: 11, color: '#9CA3AF', fontStyle: 'italic', marginTop: 4 },
  cardLabel: { fontSize: 13, fontWeight: '600' as const, color: '#374151', marginBottom: 6, marginTop: 4 },
  input: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, fontSize: 15, color: '#1F2937', backgroundColor: '#FAFAFA', marginBottom: 12 },
  cardSectionTitle: { fontSize: 15, fontWeight: '700' as const, color: '#1F2937', marginBottom: 14 },
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  toggleInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  toggleLabel: { fontSize: 15, fontWeight: '500' as const, color: '#1F2937' },
  toggleCount: { fontSize: 13, color: '#9CA3AF' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  sectionHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sectionHeaderTitle: { fontSize: 15, fontWeight: '700' as const, color: '#1F2937' },
  sectionBody: { marginTop: 14 },
  filterModeRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  filterModeButton: { flex: 1, paddingVertical: 8, borderRadius: 8, backgroundColor: '#F3F4F6', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
  filterModeButtonActive: { backgroundColor: '#7C3AED', borderColor: '#7C3AED' },
  filterModeButtonExcludeActive: { backgroundColor: '#EF4444', borderColor: '#EF4444' },
  filterModeText: { fontSize: 13, fontWeight: '600' as const, color: '#6B7280' },
  filterModeTextActive: { color: '#FFFFFF' },
  filterHint: { fontSize: 12, color: '#9CA3AF', marginBottom: 10 },
  tagGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, backgroundColor: '#F3F4F6', borderWidth: 1, borderColor: '#E5E7EB', gap: 6 },
  tagChipSelected: { backgroundColor: '#EDE9FE', borderColor: '#7C3AED' },
  tagChipExcluded: { backgroundColor: '#FEE2E2', borderColor: '#EF4444' },
  tagDot: { width: 8, height: 8, borderRadius: 4 },
  tagChipText: { fontSize: 13, color: '#374151', fontWeight: '500' as const },
  tagChipTextSelected: { color: '#1F2937', fontWeight: '600' as const },
  tagCount: { fontSize: 12, color: '#7C3AED', marginTop: 8, fontWeight: '500' as const },
  scheduleRow: { flexDirection: 'row', gap: 6, marginBottom: 8, alignItems: 'center' },
  scheduleInput: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 13, color: '#1F2937', backgroundColor: '#FAFAFA' },
  scheduleDay: { width: 80 },
  scheduleTime: { width: 80 },
  scheduleActivity: { flex: 1 },
  removeButton: { padding: 6 },
  addButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderColor: '#7C3AED', borderStyle: 'dashed', gap: 6, marginTop: 4 },
  addButtonText: { fontSize: 13, fontWeight: '600' as const, color: '#7C3AED' },
  customHint: { fontSize: 12, color: '#9CA3AF', marginBottom: 12 },
  customSectionCard: { backgroundColor: '#FAFAFA', borderRadius: 10, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#E5E7EB' },
  customSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  customTitleInput: { flex: 1, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7, fontSize: 14, fontWeight: '600' as const, color: '#1F2937', backgroundColor: '#FFFFFF' },
  disabledInput: { opacity: 0.5 },
  removeCustomButton: { padding: 6 },
  customContentInput: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 13, color: '#1F2937', backgroundColor: '#FFFFFF', marginTop: 10, minHeight: 80, textAlignVertical: 'top' },
  bottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingVertical: 12, paddingBottom: Platform.OS === 'ios' ? 28 : 12, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E5E7EB', shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 8 },
  previewButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: '#7C3AED', gap: 8 },
  previewButtonText: { fontSize: 15, fontWeight: '600' as const, color: '#7C3AED' },
  downloadButton: { flex: 2, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, backgroundColor: '#7C3AED', gap: 8 },
  downloadButtonDisabled: { opacity: 0.7 },
  downloadButtonText: { fontSize: 15, fontWeight: '600' as const, color: '#FFFFFF' },
});
