import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  logoutButton: { padding: 8 },
  pendingBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FEF3C7', paddingHorizontal: 20, paddingVertical: 12, marginHorizontal: 20, marginBottom: 16, borderRadius: 12 },
  pendingText: { marginLeft: 8, color: '#92400E', fontSize: 14, fontWeight: '500' as const },
  noDataText: { color: '#9CA3AF', fontSize: 14, textAlign: 'center' },
  roleContainer: { alignItems: 'center' },
  roleBadge: { backgroundColor: '#10B981', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginBottom: 8 },
  pendingBadge: { backgroundColor: '#F59E0B' },
  roleText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' as const },
  pendingRoleText: { color: '#FFFFFF' },
  approvedText: { color: '#6B7280', fontSize: 12 },
  familyOptions: { gap: 12 },
  familyButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#7C3AED', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 12, gap: 8 },
  secondaryButton: { backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#7C3AED' },
  familyButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' as const },
  secondaryButtonText: { color: '#7C3AED' },
  familyForm: { gap: 20 },
  formTitle: { fontSize: 16, fontWeight: '600' as const, color: '#1F2937', textAlign: 'center' },
  formSection: { gap: 12 },
  formLabel: { fontSize: 14, fontWeight: '500' as const, color: '#6B7280' },
  formInput: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 16, color: '#1F2937', marginBottom: 12, minHeight: 44 },
  submitButton: { backgroundColor: '#7C3AED', paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  submitButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' as const },
  cancelButton: { paddingVertical: 12, alignItems: 'center' },
  cancelButtonText: { color: '#6B7280', fontSize: 16 },
  divider: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#E5E7EB' },
  dividerText: { color: '#9CA3AF', fontSize: 12, fontWeight: '500' as const },
  title: { fontSize: 24, fontWeight: 'bold' as const, color: '#1F2937' },
  card: { backgroundColor: '#FFFFFF', marginHorizontal: 20, marginBottom: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  cardTitle: { fontSize: 18, fontWeight: '600' as const, color: '#1F2937' },
  editActions: { flexDirection: 'row', gap: 12 },
  iconButton: { padding: 4 },
  cardContent: { padding: 20 },
  field: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  fieldValue: { marginLeft: 12, fontSize: 16, color: '#4B5563', flex: 1 },
  editFieldContainer: { flex: 1, marginLeft: 12, gap: 8 },
  editInput: { fontSize: 16, color: '#1F2937', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', paddingVertical: 4 },
  stateZipRow: { flexDirection: 'row', gap: 12 },
  stateInput: { flex: 1 },
  zipInput: { flex: 1 },
  tokenContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 8, padding: 12, marginBottom: 8 },
  tokenText: { flex: 1, fontSize: 14, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace', color: '#1F2937' },
  copyButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#7C3AED', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6, gap: 4 },
  copyButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' as const },
  tokenHelp: { fontSize: 12, color: '#6B7280' },
  memberItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  memberAvatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  memberInfo: { flex: 1 },
  memberNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  memberName: { fontSize: 16, fontWeight: '600' as const, color: '#1F2937' },
  memberDetail: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  memberDetailText: { fontSize: 12, color: '#6B7280' },
  pendingInfo: { backgroundColor: '#EBF8FF', padding: 12, borderRadius: 8, marginBottom: 16 },
  pendingInfoText: { color: '#1E40AF', fontSize: 14, textAlign: 'center' },
  profilePrompt: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16, padding: 16, backgroundColor: '#F8FAFC', borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0' },
  profilePromptText: { flex: 1, fontSize: 14, color: '#475569', lineHeight: 20 },
  profileButton: { backgroundColor: '#7C3AED', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, paddingHorizontal: 20, borderRadius: 12, gap: 8 },
  profileButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' as const },
  addButton: { padding: 8, borderRadius: 8, backgroundColor: '#F3F4F6' },
  noAccountBadge: { backgroundColor: '#FEF3C7', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 12 },
  noAccountText: { fontSize: 10, color: '#92400E', fontWeight: '500' as const },
  addMemberForm: { backgroundColor: '#F9FAFB', borderRadius: 12, padding: 16, marginTop: 16, borderWidth: 1, borderColor: '#E5E7EB' },
  formHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  closeButton: { padding: 4 },
  formRow: { flexDirection: 'row', gap: 12 },
  halfInput: { flex: 1, marginBottom: 12 },
  checkboxContainer: { flexDirection: 'row', gap: 20, marginBottom: 16 },
  checkbox: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  checkboxInner: { width: 20, height: 20, borderRadius: 4, borderWidth: 2, borderColor: '#D1D5DB', justifyContent: 'center', alignItems: 'center' },
  checkboxChecked: { backgroundColor: '#7C3AED', borderColor: '#7C3AED' },
  checkboxLabel: { fontSize: 14, color: '#374151' },
  formActions: { marginTop: 8 },
  editMemberForm: { backgroundColor: '#F9FAFB', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E5E7EB', maxWidth: '100%' },
  memberRow: { flexDirection: 'row', alignItems: 'center' },
  editMemberButton: { padding: 8, borderRadius: 8, backgroundColor: '#F3F4F6', alignSelf: 'flex-start' },
  datePickerButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 12, minHeight: 44, backgroundColor: '#FFFFFF' },
  datePickerText: { fontSize: 16, color: '#1F2937', flex: 1 },
  placeholderText: { color: '#9CA3AF' },
  profileDateButton: { flex: 1, marginLeft: 12, borderBottomWidth: 1, borderBottomColor: '#E5E7EB', paddingVertical: 4 },
  profileDateText: { fontSize: 16, color: '#1F2937' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.3)', justifyContent: 'flex-end' },
  datePickerModal: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: Platform.OS === 'ios' ? 34 : 20, minHeight: Platform.OS === 'ios' ? 350 : 'auto' as any, shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 10 },
  datePickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#E5E7EB', backgroundColor: '#FFFFFF' },
  datePickerCancel: { fontSize: 17, color: '#007AFF', fontWeight: '400' as const },
  datePickerTitle: { fontSize: 18, fontWeight: '600' as const, color: '#1F2937' },
  datePickerDone: { fontSize: 17, color: '#007AFF', fontWeight: '600' as const },
  datePickerContainer: { backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingVertical: 10 },
  datePickerStyle: { backgroundColor: '#FFFFFF', height: Platform.OS === 'ios' ? 200 : 'auto' as any },
  familyPhotoContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 20 },
  memberAvatarContainer: { marginRight: 12 },
  memberAvatarImage: { width: 48, height: 48, borderRadius: 24 },
  meBadge: { backgroundColor: '#7C3AED', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 12 },
  meText: { fontSize: 10, color: '#FFFFFF', fontWeight: '600' as const },
  memberTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  manageTagsButton: { backgroundColor: '#F3F4F6', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginTop: 8, alignSelf: 'flex-start' },
  manageTagsText: { fontSize: 12, color: '#7C3AED', fontWeight: '500' as const },
  modalContainer: { flex: 1, backgroundColor: '#F9FAFB' },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  modalCloseButton: { padding: 8, borderRadius: 8, backgroundColor: '#F3F4F6' },
  modalTitle: { fontSize: 18, fontWeight: '600' as const, color: '#1F2937' },
  modalContent: { flex: 1, paddingHorizontal: 20 },
  modalPlaceholder: { width: 40 },
});
