import { StyleSheet, Platform } from 'react-native';

export const visitorProfileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { paddingHorizontal: 20, paddingVertical: 32, alignItems: 'center' },
  headerContent: { alignItems: 'center' },
  iconContainer: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#EDE9FE', justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  title: { fontSize: 28, fontWeight: 'bold' as const, color: '#1F2937', marginBottom: 8, textAlign: 'center' as const },
  subtitle: { fontSize: 16, color: '#6B7280', textAlign: 'center' as const, lineHeight: 24 },
  card: { backgroundColor: '#FFFFFF', marginHorizontal: 20, marginBottom: 16, borderRadius: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  cardHeader: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  cardTitle: { fontSize: 18, fontWeight: '600' as const, color: '#1F2937' },
  cardContent: { padding: 20 },
  avatarContainer: { alignItems: 'center' as const, marginBottom: 12 },
  avatarHelp: { fontSize: 14, color: '#6B7280', textAlign: 'center' as const },
  formRow: { flexDirection: 'row' as const, gap: 12 },
  inputContainer: { flex: 1, marginBottom: 16 },
  inputLabel: { fontSize: 14, fontWeight: '500' as const, color: '#374151', marginBottom: 6 },
  input: { borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, fontSize: 16, color: '#1F2937', backgroundColor: '#FFFFFF' },
  inputWithIcon: { flexDirection: 'row' as const, alignItems: 'center' as const, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, backgroundColor: '#FFFFFF' },
  inputIcon: { marginLeft: 12 },
  inputWithIconText: { flex: 1, paddingHorizontal: 12, paddingVertical: 12, fontSize: 16, color: '#1F2937' },
  datePickerButton: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, backgroundColor: '#FFFFFF' },
  datePickerText: { fontSize: 16, color: '#1F2937', flex: 1 },
  placeholderText: { color: '#9CA3AF' },
  pendingNotice: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, backgroundColor: '#FEF3C7', marginHorizontal: 20, marginBottom: 24, padding: 16, borderRadius: 12, gap: 12 },
  pendingNoticeText: { flex: 1, fontSize: 14, color: '#92400E', lineHeight: 20 },
  actions: { paddingHorizontal: 20, paddingBottom: 32, gap: 12 },
  saveButton: { backgroundColor: '#7C3AED', borderRadius: 12, paddingVertical: 16, flexDirection: 'row' as const, justifyContent: 'center' as const, alignItems: 'center' as const, gap: 8 },
  saveButtonDisabled: { opacity: 0.7 },
  saveButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' as const },
  skipButton: { paddingVertical: 16, alignItems: 'center' as const },
  skipButtonText: { color: '#6B7280', fontSize: 16, fontWeight: '500' as const },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.3)', justifyContent: 'flex-end' as const },
  datePickerModal: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: Platform.OS === 'ios' ? 34 : 20, minHeight: Platform.OS === 'ios' ? 350 : 'auto' as any, shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 10 },
  datePickerHeader: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#E5E7EB', backgroundColor: '#FFFFFF' },
  datePickerCancel: { fontSize: 17, color: '#007AFF', fontWeight: '400' as const },
  datePickerTitle: { fontSize: 18, fontWeight: '600' as const, color: '#1F2937' },
  datePickerDone: { fontSize: 17, color: '#007AFF', fontWeight: '600' as const },
  datePickerContainer: { backgroundColor: '#FFFFFF', paddingHorizontal: 20, paddingVertical: 10 },
  datePickerStyle: { backgroundColor: '#FFFFFF', height: Platform.OS === 'ios' ? 200 : 'auto' as any },
});
