import { StyleSheet } from 'react-native';

export const potluckFormStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFBEB' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  headerCard: { backgroundColor: '#FEF3C7', borderRadius: 14, padding: 18, marginBottom: 20, borderWidth: 1, borderColor: '#FDE68A' },
  headerIconRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  headerIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#FDE68A', justifyContent: 'center', alignItems: 'center' },
  headerTitle: { fontSize: 20, fontWeight: '700' as const, color: '#92400E' },
  headerSub: { fontSize: 14, color: '#A16207', lineHeight: 20 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 17, fontWeight: '700' as const, color: '#111827', marginBottom: 12 },
  label: { fontSize: 14, fontWeight: '600' as const, color: '#374151', marginBottom: 6, marginTop: 10 },
  input: { backgroundColor: '#fff', borderRadius: 10, padding: 14, fontSize: 15, color: '#111827', borderWidth: 1, borderColor: '#D1D5DB' },
  textArea: { minHeight: 80, paddingTop: 14 },
  switchRow: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const, marginTop: 14 },
  switchLabel: { fontSize: 15, color: '#374151', fontWeight: '500' as const },
  dateBtn: { backgroundColor: '#FEF3C7', borderRadius: 10, padding: 14, marginTop: 10, alignItems: 'center' as const, borderWidth: 1, borderColor: '#FDE68A' },
  dateBtnText: { fontSize: 15, color: '#92400E', fontWeight: '500' as const },
  doneBtn: { alignSelf: 'flex-end' as const, paddingHorizontal: 20, paddingVertical: 8, marginTop: 6 },
  doneBtnText: { color: '#D97706', fontWeight: '600' as const, fontSize: 15 },
  suggestRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, marginBottom: 14 },
  suggestLabel: { fontSize: 13, color: '#6B7280', fontWeight: '500' as const },
  suggestScroll: { flexGrow: 0 },
  suggestChip: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#FDE68A', backgroundColor: '#FEF3C7', marginRight: 6 },
  suggestChipText: { fontSize: 12, fontWeight: '600' as const, color: '#D97706' },
  groupCard: { backgroundColor: '#fff', borderRadius: 14, marginBottom: 14, borderWidth: 1, borderColor: '#E5E7EB', overflow: 'hidden' as const },
  groupHeader: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: '#F9FAFB', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  groupCollapseBtn: { padding: 4, marginRight: 4 },
  groupTitleInput: { flex: 1, fontSize: 15, fontWeight: '700' as const, color: '#111827', paddingVertical: 4 },
  groupActions: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 2 },
  miniIconBtn: { padding: 6 },
  groupBody: { padding: 12 },
  collapsedInfo: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, paddingHorizontal: 16, paddingVertical: 10 },
  collapsedText: { fontSize: 13, color: '#9CA3AF' },
  itemRow: { marginBottom: 12 },
  itemMain: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 8 },
  itemNumberBadge: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#FEF3C7', justifyContent: 'center' as const, alignItems: 'center' as const, marginTop: 10 },
  itemNumber: { fontSize: 11, fontWeight: '700' as const, color: '#D97706' },
  itemFields: { flex: 1 },
  itemNameInput: { backgroundColor: '#F9FAFB', borderRadius: 8, padding: 10, fontSize: 14, color: '#111827', borderWidth: 1, borderColor: '#E5E7EB', marginBottom: 4 },
  itemDescInput: { backgroundColor: '#F9FAFB', borderRadius: 8, padding: 8, fontSize: 13, color: '#6B7280', borderWidth: 1, borderColor: '#F3F4F6', marginBottom: 4 },
  qtyRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, marginTop: 2 },
  qtyLabel: { fontSize: 12, color: '#6B7280', fontWeight: '500' as const },
  qtyBtn: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F3F4F6', justifyContent: 'center' as const, alignItems: 'center' as const, borderWidth: 1, borderColor: '#D1D5DB' },
  qtyBtnText: { fontSize: 16, fontWeight: '600' as const, color: '#374151', lineHeight: 18 },
  qtyValue: { fontSize: 15, fontWeight: '700' as const, color: '#111827', minWidth: 20, textAlign: 'center' as const },
  itemDeleteBtn: { padding: 8, marginTop: 6 },
  addItemBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 6, paddingVertical: 10, borderRadius: 8, borderWidth: 1, borderStyle: 'dashed' as const, borderColor: '#FDE68A', backgroundColor: '#FFFBEB' },
  addItemBtnText: { fontSize: 14, fontWeight: '600' as const, color: '#D97706' },
  addGroupBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, justifyContent: 'center' as const, gap: 8, paddingVertical: 14, borderRadius: 12, borderWidth: 1.5, borderColor: '#FDE68A', borderStyle: 'dashed' as const, backgroundColor: '#FFFBEB', marginTop: 4 },
  addGroupBtnText: { fontSize: 15, fontWeight: '600' as const, color: '#D97706' },
  submitBtn: { backgroundColor: '#D97706', borderRadius: 12, paddingVertical: 16, alignItems: 'center' as const, marginTop: 8 },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' as const },
});
