import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  title: { fontSize: 24, fontWeight: 'bold' as const, color: '#1F2937' },
  searchContainer: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', gap: 12 },
  searchInputContainer: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9FAFB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  searchInput: { flex: 1, fontSize: 16, color: '#1F2937' },
  clearButton: { padding: 4 },
  filterButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: '#F9FAFB', borderWidth: 1, borderColor: '#7C3AED', gap: 6 },
  filterButtonActive: { backgroundColor: '#7C3AED', borderColor: '#7C3AED' },
  filterButtonText: { fontSize: 14, color: '#7C3AED', fontWeight: '500' as const },
  filterButtonTextActive: { color: '#FFFFFF' },
  createButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#7C3AED', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, gap: 6 },
  createButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' as const },
  listContainer: { padding: 16, paddingBottom: 100 },
  eventCard: { backgroundColor: '#FFFFFF', borderRadius: 12, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  eventImage: { width: '100%', height: 200, borderTopLeftRadius: 12, borderTopRightRadius: 12 },
  eventContent: { padding: 16 },
  eventTitle: { fontSize: 18, fontWeight: '600' as const, color: '#111827', marginBottom: 8 },
  eventMeta: { marginBottom: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  metaText: { fontSize: 14, color: '#6B7280', marginLeft: 8, flex: 1 },
  eventDescription: { fontSize: 14, color: '#4B5563', lineHeight: 20, marginBottom: 16 },
  eventActions: { gap: 12 },
  rsvpContainer: { flexDirection: 'row', gap: 8 },
  rsvpButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: '#D1D5DB', alignItems: 'center' },
  rsvpButtonActive: { borderColor: '#7C3AED' },
  rsvpButtonGoing: { backgroundColor: '#10B981', borderColor: '#10B981' },
  rsvpButtonMaybe: { backgroundColor: '#F59E0B', borderColor: '#F59E0B' },
  rsvpButtonDeclined: { backgroundColor: '#EF4444', borderColor: '#EF4444' },
  rsvpButtonText: { fontSize: 14, color: '#6B7280', fontWeight: '500' as const },
  rsvpButtonTextActive: { color: '#FFFFFF' },
  calendarButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8, borderWidth: 1, borderColor: '#7C3AED', gap: 8 },
  calendarButtonText: { fontSize: 14, color: '#7C3AED', fontWeight: '500' as const },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 64 },
  emptyText: { fontSize: 18, fontWeight: '600' as const, color: '#4B5563', marginTop: 16 },
  emptySubtext: { fontSize: 14, color: '#9CA3AF', marginTop: 4 },
  viewModeToggle: { flexDirection: 'row', backgroundColor: '#F3F4F6', borderRadius: 8, padding: 4, marginBottom: 16 },
  toggleButton: { flex: 1, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 6, alignItems: 'center' },
  toggleButtonActive: { backgroundColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },
  toggleButtonText: { fontSize: 14, fontWeight: '500' as const, color: '#6B7280' },
  toggleButtonTextActive: { color: '#7C3AED', fontWeight: '600' as const },
  filtersContainer: { backgroundColor: '#FFFFFF', marginBottom: 16, borderRadius: 12, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  filterHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  filterTitle: { fontSize: 18, fontWeight: '600' as const, color: '#111827' },
  filterSection: { marginBottom: 16 },
  filterLabel: { fontSize: 14, fontWeight: '500' as const, color: '#374151', marginBottom: 8 },
  filterOptions: { flexDirection: 'row' },
  filterChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#D1D5DB', marginRight: 8, backgroundColor: '#FFFFFF' },
  filterChipActive: { borderColor: '#7C3AED', backgroundColor: '#7C3AED' },
  filterChipGoing: { backgroundColor: '#10B981', borderColor: '#10B981' },
  filterChipMaybe: { backgroundColor: '#F59E0B', borderColor: '#F59E0B' },
  filterChipDeclined: { backgroundColor: '#EF4444', borderColor: '#EF4444' },
  filterChipText: { fontSize: 12, color: '#6B7280', fontWeight: '500' as const },
  filterChipTextActive: { color: '#FFFFFF' },
  clearFiltersButton: { alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: '#EF4444' },
  clearFiltersText: { fontSize: 14, color: '#EF4444', fontWeight: '500' as const },
  activeFiltersContainer: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 16, paddingHorizontal: 4 },
  activeFiltersText: { fontSize: 14, color: '#6B7280', fontWeight: '500' as const },
  activeFilterChip: { backgroundColor: '#EEF2FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  activeFilterChipText: { fontSize: 12, color: '#7C3AED', fontWeight: '500' as const },
  tagFilterChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#D1D5DB', marginRight: 8, backgroundColor: '#FFFFFF' },
  tagFilterChipActive: { borderColor: 'transparent' },
  tagFilterText: { fontSize: 12, fontWeight: '500' as const },
  tagFilterTextActive: { color: '#FFFFFF' },
  eventTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 12 },
  formBadge: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, marginBottom: 12 },
  formBadgePotluck: { backgroundColor: '#FEF3C7', borderWidth: 1, borderColor: '#FDE68A' },
  formBadgeSignup: { backgroundColor: '#EEF2FF', borderWidth: 1, borderColor: '#C7D2FE' },
  formBadgeText: { fontSize: 13, fontWeight: '600' as const },
  formBadgeTextPotluck: { color: '#92400E' },
  formBadgeTextSignup: { color: '#312E81' },
  headerButtons: { flexDirection: 'row', gap: 8 },
});
