import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFBEB',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    padding: 32,
  },
  loadingText: {
    fontSize: 15,
    color: '#92400E',
    marginTop: 12,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#374151',
    marginTop: 12,
  },
  errorSub: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center' as const,
    marginTop: 6,
    marginBottom: 16,
  },
  retryBtn: {
    backgroundColor: '#D97706',
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 12,
  },
  retryBtnText: {
    color: '#fff',
    fontWeight: '600' as const,
    fontSize: 15,
  },
  progressBar: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#FDE68A',
  },
  progressInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#92400E',
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#FDE68A',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    backgroundColor: '#D97706',
    borderRadius: 3,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  descBox: {
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  descText: {
    fontSize: 14,
    color: '#92400E',
    lineHeight: 20,
  },
  groupSection: {
    marginBottom: 20,
  },
  groupTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  groupTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#111827',
  },
  groupCount: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#D97706',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
  },
  itemCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
  },
  itemCardFull: {
    opacity: 0.7,
    borderColor: '#D1FAE5',
    backgroundColor: '#F0FDF4',
  },
  itemCardMine: {
    borderColor: '#FDE68A',
    borderWidth: 2,
  },
  itemCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
  },
  itemCardInfo: {
    flex: 1,
    marginRight: 10,
  },
  itemNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: '#111827',
  },
  itemNameFull: {
    color: '#065F46',
  },
  itemDesc: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 3,
  },
  itemStatus: {
    fontSize: 12,
    color: '#D97706',
    fontWeight: '500' as const,
    marginTop: 4,
  },
  itemStatusFull: {
    color: '#10B981',
  },
  claimBtn: {
    backgroundColor: '#D97706',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  claimBtnText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#fff',
  },
  claimsList: {
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  claimRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  claimRowMine: {
    backgroundColor: '#FFFBEB',
    marginHorizontal: -14,
    paddingHorizontal: 14,
  },
  claimInfo: {
    flex: 1,
  },
  claimName: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500' as const,
  },
  claimNameMine: {
    color: '#D97706',
    fontWeight: '600' as const,
  },
  claimNoteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
  },
  claimNoteText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontStyle: 'italic' as const,
  },
  unclaimBtn: {
    padding: 6,
    backgroundColor: '#FEE2E2',
    borderRadius: 6,
  },
  addItemInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#FDE68A',
    marginTop: 4,
  },
  addItemInlineText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: '#D97706',
  },
  addGroupInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#FDE68A',
    backgroundColor: '#FEF3C7',
  },
  addGroupInlineText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#D97706',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    paddingBottom: 30,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: '#111827',
    flex: 1,
    marginRight: 12,
  },
  modalClose: {
    padding: 4,
  },
  modalScroll: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#374151',
    marginBottom: 8,
    marginTop: 12,
  },
  modeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  modeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#FDE68A',
    backgroundColor: '#FFFBEB',
  },
  modeBtnActive: {
    backgroundColor: '#D97706',
    borderColor: '#D97706',
  },
  modeBtnText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#D97706',
  },
  modeBtnTextActive: {
    color: '#fff',
  },
  selectedPersonCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEF3C7',
    borderRadius: 10,
    padding: 12,
    marginBottom: 4,
  },
  selectedPersonName: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#92400E',
    flex: 1,
  },
  pickerBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 6,
  },
  pickerBtnText: {
    fontSize: 15,
    color: '#374151',
  },
  pickerList: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    marginBottom: 6,
  },
  pickerItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  pickerItemActive: {
    backgroundColor: '#FEF3C7',
  },
  pickerItemText: {
    fontSize: 15,
    color: '#374151',
  },
  pickerItemTextActive: {
    color: '#D97706',
    fontWeight: '600' as const,
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 6,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: '#111827',
  },
  modalInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 14,
    fontSize: 15,
    color: '#111827',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginBottom: 8,
  },
  noteInput: {
    minHeight: 60,
    paddingTop: 14,
  },
  claimSubmitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#D97706',
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  btnDisabled: {
    opacity: 0.6,
  },
  claimSubmitText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700' as const,
  },
  newItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  miniQtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  miniQtyBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  miniQtyBtnText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#374151',
    lineHeight: 17,
  },
  miniQtyValue: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#111827',
    minWidth: 18,
    textAlign: 'center' as const,
  },
  addMoreItemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#FDE68A',
    marginBottom: 8,
  },
  addMoreItemText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#D97706',
  },
});
