import { StyleSheet } from 'react-native';

export const signupFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 15,
    color: '#6B7280',
  },
  errorText: {
    fontSize: 16,
    color: '#DC2626',
    fontWeight: '600' as const,
    marginBottom: 16,
  },
  backBtn: {
    backgroundColor: '#4338CA',
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
  },
  backBtnText: {
    color: '#fff',
    fontWeight: '600' as const,
    fontSize: 15,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: '#111827',
    marginBottom: 12,
  },
  label: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#374151',
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    fontSize: 15,
    color: '#111827',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  textArea: {
    minHeight: 80,
    paddingTop: 14,
  },
  switchRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginTop: 14,
  },
  switchLabel: {
    fontSize: 15,
    color: '#374151',
    fontWeight: '500' as const,
  },
  dateBtn: {
    backgroundColor: '#EEF2FF',
    borderRadius: 10,
    padding: 14,
    marginTop: 10,
    alignItems: 'center' as const,
  },
  dateBtnText: {
    fontSize: 15,
    color: '#4338CA',
    fontWeight: '500' as const,
  },
  doneBtn: {
    alignSelf: 'flex-end' as const,
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginTop: 6,
  },
  doneBtnText: {
    color: '#4338CA',
    fontWeight: '600' as const,
    fontSize: 15,
  },
  inactiveWarning: {
    fontSize: 13,
    color: '#DC2626',
    marginTop: 6,
    fontWeight: '500' as const,
  },
  quickAddRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
    marginBottom: 14,
  },
  quickAddLabel: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500' as const,
  },
  quickAddBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    backgroundColor: '#EEF2FF',
  },
  quickAddBtnDisabled: {
    opacity: 0.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  quickAddBtnText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#4338CA',
  },
  quickAddBtnTextDisabled: {
    color: '#9CA3AF',
  },
  warningBanner: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    backgroundColor: '#FFFBEB',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  warningText: {
    fontSize: 13,
    color: '#92400E',
    flex: 1,
  },
  fieldCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden' as const,
  },
  fieldCardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    padding: 12,
  },
  fieldCardLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    flex: 1,
  },
  standardBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 3,
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  standardBadgeText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: '#4338CA',
  },
  fieldCardTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#111827',
    flex: 1,
  },
  fieldCardActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 2,
  },
  iconBtn: {
    padding: 6,
  },
  fieldCardBody: {
    padding: 12,
    paddingTop: 0,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  miniLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#6B7280',
    marginBottom: 4,
    marginTop: 10,
  },
  miniInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#111827',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  typeRow: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 6,
  },
  typeChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
  },
  typeChipActive: {
    backgroundColor: '#4338CA',
    borderColor: '#4338CA',
  },
  typeChipText: {
    fontSize: 12,
    color: '#374151',
    fontWeight: '500' as const,
  },
  typeChipTextActive: {
    color: '#fff',
  },
  optionsSection: {
    marginTop: 4,
  },
  optionRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 6,
    marginBottom: 4,
  },
  optionText: {
    fontSize: 14,
    color: '#374151',
  },
  addOptionRow: {
    flexDirection: 'row' as const,
    gap: 8,
    marginTop: 4,
  },
  addOptionBtn: {
    backgroundColor: '#4338CA',
    borderRadius: 8,
    width: 36,
    height: 36,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  addFieldBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#C7D2FE',
    borderStyle: 'dashed' as const,
    backgroundColor: '#FAFAFF',
    marginTop: 4,
  },
  addFieldBtnText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#4338CA',
  },
  submitBtn: {
    backgroundColor: '#4338CA',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center' as const,
    marginTop: 8,
  },
  submitBtnDisabled: {
    opacity: 0.6,
  },
  submitBtnText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700' as const,
  },
});
